name: suns_med
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+8

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # contacts_service: ^0.3.10
  flutter_rating_bar: ^3.2.0+1
  expandable: ^4.1.4
  # country_pickers: ^1.1.0
  cupertino_icons: ^0.1.3
  google_maps_flutter: ^1.0.3
  table_calendar: ^2.2.3
  image_picker: ^0.6.7+22
  intl: ^0.16.0
  # mime: ^0.9.7
  # progress_dialog: ^1.2.4
  dotted_border: ^1.0.6
  fl_animated_linechart: ^1.1.3
  path_provider:
  shared_preferences: ^0.5.10
  cached_network_image: ^2.3.3
  flutter_html: ^0.10.1+hotfix.1
  # dio: ^3.0.9
  timeago: ^2.0.29
  http: ^0.12.2
  # json_serializable: ^3.3.0
  flushbar: ^1.10.4
  shimmer: ^1.1.2
  qr_flutter: ^3.1.0
  webview_flutter: ^1.0.7
  url_launcher: ^5.7.10
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  photo_view: ^0.10.3
  share: ^0.6.5+4
  pattern_formatter: ^1.0.2
  flutter_masked_text: ^0.7.0
  permission_handler: ^5.1.0+2
  onesignal_flutter: ^2.6.2
  momo_vn: ^1.0.3
  fluttertoast: ^7.1.8
  fw_ticket: any
  flutter_keyboard_visibility: ^4.0.6
  barcode_scan: ^2.0.1
  geolocator: ^5.3.2+2
  universal_html: ^1.2.1
  flutter_icons: ^1.1.0
  flutter_webrtc: ^0.3.3
  signalr_core: ^1.0.5
  provider: ^4.1.3
  socket_io_client: ^0.9.9
  location_permissions: 3.0.0+1
  flutter_typeahead: ^2.0.0
  age: ^0.0.1
  flutter_slidable: ^0.5.7
  carousel_slider: ^2.2.1
  sticky_headers: ^0.1.0
  package_info_plus: ^0.6.4
  flutter_svg: ^0.9.0+1


  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_native_splash: ^0.3.2

# flutter_native_splash:

#   android: true
#   ios: true
#   web: false

#   color: "#FFFFFF"
#   # background_image: "assets/splash_screen/splash.png"
#   image: assets/splash_screen/splash.png

#   android_gravity: fill
#   ios_content_mode: fill

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts: 
    - family: Montserrat-B
      fonts:
        - asset: assets/fonts/Montserrat-B.ttf
          weight: 700
    - family: Montserrat-M
      fonts:
        - asset: assets/fonts/Montserrat-M.ttf
          weight: 400
  generate: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/splash_screen/
    - assets/imgclinic/
    - assets/images/images2x/
    - assets/images/images3x/
    - assets/images/profile/
    - assets/images/accounts/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
