class Doctor {
  final int favorite;
  final double totalRate;
  final String image,
      title,
      name,
      specialist,
      address,
      phone,
      email,
      location,
      nameH,
      time,
      rating,
      feedback,
      education;

  Doctor({
    this.totalRate,
    this.image,
    this.name,
    this.title,
    this.specialist,
    this.address,
    this.favorite,
    this.phone,
    this.email,
    this.location,
    this.nameH,
    this.time,
    this.feedback,
    this.rating,
    this.education,
  });
}

final List<Doctor> feedbacks = [
  Doctor(
      image: 'assets/images/feedback.png',
      name: 'Lộc Tiến',
      rating: '(4)',
      feedback: 'Khá tốt'),
  Doctor(
      image: 'assets/images/feedback.png',
      name: 'Lộc Tiến',
      rating: '(4)',
      feedback: 'Khá tốt'),
  Doctor(
      image: 'assets/images/feedback.png',
      name: 'Lộc Tiến',
      rating: '(4)',
      feedback: 'Khá tốt'),
  Doctor(
      image: 'assets/images/feedback.png',
      name: 'Lộc Tiến',
      rating: '(4)',
      feedback: 'Khá tốt'),
];

final List<Doctor> doctorList = [
  Doctor(
      image: 'assets/images/123.jpg',
      name: 'Bác sĩ: Võ Nhị Anh',
      title: 'Bác sĩ - Chuyên gia khoa tai mũi họng',
      specialist: 'Chuyên khoa: Tai mũi họng',
      address: '527 Sư Vạn Hạnh, quận 10, HCM',
      favorite: 5,
      phone: '0948819199',
      email: 'vnhianh.it@gmail.com',
      location: '255 Phố Huế, Hai Bà Trưng, Hà Nội',
      nameH: 'Hệ thống nha khoa thẩm mĩ quốc tế',
      time: 'Th2 - CN từ 9h - 20h',
      rating: '45 đánh giá',
      education:
          'Từ năm 2006 – 2012: Tốt nghiệp Viện đào tạo răng hàm mặt Đại học Y Hà Nội Từ năm 2013 – nay: Tham gia khóa đào tạo thực hành “Thiết kế nụ cười trong Nha khoa” cùng Dr. David Montalvo Arias (hiện đang làm việc tại Apa Aesthetics UAE) bậc thầy trong Thiết kế nụ cười Tham gia khóa đào tạo chuyên sâu “ Thẩm mỹ nội khoa không dao kéo” cùng Dr. David Dana (Education Director tại Progressive Orthodontic Seminars) Tham gia khóa đào tạo Phục hình Inlay, Công nghệ sứ sinh học trong phục hồi răng thẩm mỹ do Mani Schutz Dental tổ chức.'),
  Doctor(
    image: 'assets/images/doctor2.png',
    name: 'Bác sĩ: Nguyễn Hải Thiên',
    title: 'Bác sĩ - Chuyên gia thiết kế nụ cười Khả Lệ',
    specialist: 'Chuyên khoa: Răng hàm mặt',
    address: '527 Sư Vạn Hạnh, quận 10, HCM',
    favorite: 5,
    phone: '0966216565',
    email: 'Nhakhoatrendsmile@gmail.com',
    location: '255 Phố Huế, Hai Bà Trưng, Hà Nội',
    nameH: 'Hệ thống nha khoa thẩm mĩ quốc tế',
    time: 'Th2 - CN từ 9h - 20h',
    rating: '45 đánh giá',
    education:
        'Từ năm 2006 – 2012: Tốt nghiệp Viện đào tạo răng hàm mặt Đại học Y Hà Nội',
  ),
  Doctor(
    image: 'assets/images/doctor3.png',
    name: 'Bác sĩ: Nguyễn Hải Em',
    title: 'Bác sĩ - Chuyên gia thiết kế nụ cười Khả Lệ',
    specialist: 'Chuyên khoa: Răng hàm mặt',
    address: '527 Sư Vạn Hạnh, quận 10, HCM',
    favorite: 5,
    phone: '0966216565',
    email: 'Nhakhoatrendsmile@gmail.com',
    location: '255 Phố Huế, Hai Bà Trưng, Hà Nội',
    nameH: 'Hệ thống nha khoa thẩm mĩ quốc tế',
    time: 'Th2 - CN từ 9h - 20h',
    rating: '45 đánh giá',
    education:
        'Từ năm 2006 – 2012: Tốt nghiệp Viện đào tạo răng hàm mặt Đại học Y Hà Nội',
  ),
  Doctor(
    image: 'assets/images/doctor.png',
    name: 'Bác sĩ: Nguyễn Hải Anh',
    title: 'Bác sĩ - Chuyên gia thiết kế nụ cười Khả Lệ',
    specialist: 'Chuyên khoa: Răng hàm mặt',
    address: '527 Sư Vạn Hạnh, quận 10, HCM',
    favorite: 5,
    phone: '0966216565',
    email: 'Nhakhoatrendsmile@gmail.com',
    location: '255 Phố Huế, Hai Bà Trưng, Hà Nội',
    nameH: 'Hệ thống nha khoa thẩm mĩ quốc tế',
    time: 'Th2 - CN từ 9h - 20h',
    rating: '45 đánh giá',
    education:
        'Từ năm 2006 – 2012: Tốt nghiệp Viện đào tạo răng hàm mặt Đại học Y Hà Nội',
  ),
  Doctor(
      image: 'assets/images/doctor2.png',
      name: 'Bác sĩ: Nguyễn Hải Thiên',
      title: 'Bác sĩ - Chuyên gia thiết kế nụ cười Khả Lệ',
      specialist: 'Chuyên khoa: Răng hàm mặt',
      address: '527 Sư Vạn Hạnh, quận 10, HCM',
      favorite: 5,
      phone: '0966216565',
      email: 'Nhakhoatrendsmile@gmail.com',
      location: '255 Phố Huế, Hai Bà Trưng, Hà Nội',
      nameH: 'Hệ thống nha khoa thẩm mĩ quốc tế',
      time: 'Th2 - CN từ 9h - 20h',
      rating: '45 đánh giá',
      education:
          'Từ năm 2006 – 2012: Tốt nghiệp Viện đào tạo răng hàm mặt Đại học Y Hà Nội Từ năm 2013 – nay: Tham gia khóa đào tạo thực hành “Thiết kế nụ cười trong Nha khoa” cùng Dr. David Montalvo Arias (hiện đang làm việc tại Apa Aesthetics UAE) bậc thầy trong Thiết kế nụ cười Tham gia khóa đào tạo chuyên sâu “ Thẩm mỹ nội khoa không dao kéo” cùng Dr. David Dana (Education Director tại Progressive Orthodontic Seminars) Tham gia khóa đào tạo Phục hình Inlay, Công nghệ sứ sinh học trong phục hồi răng thẩm mỹ do Mani Schutz Dental tổ chức.'),
  Doctor(
    image: 'assets/images/doctor3.png',
    name: 'Bác sĩ: Nguyễn Hải Em',
    title: 'Bác sĩ - Chuyên gia thiết kế nụ cười Khả Lệ',
    specialist: 'Chuyên khoa: Răng hàm mặt',
    address: '527 Sư Vạn Hạnh, quận 10, HCM',
    favorite: 5,
    phone: '0966216565',
    email: 'Nhakhoatrendsmile@gmail.com',
    location: '255 Phố Huế, Hai Bà Trưng, Hà Nội',
    nameH: 'Hệ thống nha khoa thẩm mĩ quốc tế',
    time: 'Th2 - CN từ 9h - 20h',
    rating: '45 đánh giá',
    education:
        'Từ năm 2006 – 2012: Tốt nghiệp Viện đào tạo răng hàm mặt Đại học Y Hà Nội',
  ),
  Doctor(
    image: 'assets/images/doctor.png',
    name: 'Bác sĩ: Nguyễn Hải Anh',
    title: 'Bác sĩ - Chuyên gia thiết kế nụ cười Khả Lệ',
    specialist: 'Chuyên khoa: Răng hàm mặt',
    address: '527 Sư Vạn Hạnh, quận 10, HCM',
    favorite: 5,
    phone: '0966216565',
    email: 'Nhakhoatrendsmile@gmail.com',
    location: '255 Phố Huế, Hai Bà Trưng, Hà Nội',
    nameH: 'Hệ thống nha khoa thẩm mĩ quốc tế',
    time: 'Th2 - CN từ 9h - 20h',
    rating: '45 đánh giá',
    education:
        'Từ năm 2006 – 2012: Tốt nghiệp Viện đào tạo răng hàm mặt Đại học Y Hà Nội',
  ),
];
final List<Doctor> doctorPopular = [
  Doctor(
    image: 'assets/images/doctor.png',
    name: 'Bác sĩ: Nguyễn Hải Anh',
    title: 'Bác sĩ - Chuyên gia thiết kế nụ cười Khả Lệ',
    specialist: 'Chuyên khoa: Răng hàm mặt',
    address: '527 Sư Vạn Hạnh, quận 10, HCM',
    favorite: 5,
    phone: '0966216565',
    email: 'Nhakhoatrendsmile@gmail.com',
    location: '255 Phố Huế, Hai Bà Trưng, Hà Nội',
    nameH: 'Hệ thống nha khoa thẩm mĩ quốc tế',
    time: 'Th2 - CN từ 9h - 20h',
    rating: '45 đánh giá',
    education:
        'Từ năm 2006 – 2012: Tốt nghiệp Viện đào tạo răng hàm mặt Đại học Y Hà Nội',
  ),
  Doctor(
    image: 'assets/images/doctor2.png',
    name: 'Bác sĩ: Nguyễn Hải Thiên',
    title: 'Bác sĩ - Chuyên gia thiết kế nụ cười Khả Lệ',
    specialist: 'Chuyên khoa: Răng hàm mặt',
    address: '527 Sư Vạn Hạnh, quận 10, HCM',
    favorite: 5,
    phone: '0966216565',
    email: 'Nhakhoatrendsmile@gmail.com',
    location: '255 Phố Huế, Hai Bà Trưng, Hà Nội',
    nameH: 'Hệ thống nha khoa thẩm mĩ quốc tế',
    time: 'Th2 - CN từ 9h - 20h',
    rating: '45 đánh giá',
    education:
        'Từ năm 2006 – 2012: Tốt nghiệp Viện đào tạo răng hàm mặt Đại học Y Hà Nội',
  ),
  Doctor(
    image: 'assets/images/doctor3.png',
    name: 'Bác sĩ: Nguyễn Hải Em',
    title: 'Bác sĩ - Chuyên gia thiết kế nụ cười Khả Lệ',
    specialist: 'Chuyên khoa: Răng hàm mặt',
    address: '527 Sư Vạn Hạnh, quận 10, HCM',
    favorite: 5,
    phone: '0966216565',
    email: 'Nhakhoatrendsmile@gmail.com',
    location: '255 Phố Huế, Hai Bà Trưng, Hà Nội',
    nameH: 'Hệ thống nha khoa thẩm mĩ quốc tế',
    time: 'Th2 - CN từ 9h - 20h',
    education:
        'Từ năm 2006 – 2012: Tốt nghiệp Viện đào tạo răng hàm mặt Đại học Y Hà Nội',
  ),
];
final List<Doctor> clinicList = [
  Doctor(
    image: 'assets/images/hospital4.png',
    name: 'Phòng khám đa khoa An Khang',
    specialist: 'Chuyên khoa: Răng hàm mặt',
    address: '527 Sư Vạn Hạnh, quận 10, HCM',
    totalRate: 4.5,
    favorite: 5,
  ),
  Doctor(
    image: 'assets/images/hospital1.png',
    name: 'Phòng khám đa khoa An Khang',
    specialist: 'Chuyên khoa: Răng hàm mặt',
    address: '527 Sư Vạn Hạnh, quận 10, HCM',
    totalRate: 4.5,
    favorite: 5,
  ),
];
final List<Doctor> hospitalList = [
  Doctor(
    image: 'assets/images/hospital3.png',
    name: 'Bệnh viện quận Thủ Đức',
    specialist: 'Chuyên khoa: Răng hàm mặt',
    address: '527 Sư Vạn Hạnh, quận 10, HCM',
    totalRate: 4.5,
    favorite: 5,
  ),
  Doctor(
    image: 'assets/images/hospital2.png',
    name: 'Bệnh viện quận Thủ Đức',
    specialist: 'Chuyên khoa: Răng hàm mặt',
    address: '527 Sư Vạn Hạnh, quận 10, HCM',
    totalRate: 4.5,
    favorite: 5,
  ),
];

final List<Doctor> hospitalPopular = [
  Doctor(
    image: 'assets/images/hospital3.png',
    name: 'Bệnh viện quận Thủ Đức',
    specialist: 'Chuyên khoa: Răng hàm mặt',
    address: '527 Sư Vạn Hạnh, quận 10, HCM',
    totalRate: 4.5,
    favorite: 5,
  ),
  Doctor(
    image: 'assets/images/hospital2.png',
    name: 'Bệnh viện quận Thủ Đức',
    specialist: 'Chuyên khoa: Răng hàm mặt',
    address: '527 Sư Vạn Hạnh, quận 10, HCM',
    totalRate: 4.5,
    favorite: 5,
  ),
];

final List<Doctor> stomach = [
  Doctor(
      image: 'assets/images/doctor2.png',
      name: 'Bác sĩ: Đồ Long Đao',
      title: 'Bác sĩ - Chuyên gia bộ đồ lòng',
      specialist: 'Chuyên khoa: Tiêu hóa - Gan mật',
      address: '527 Sư Vạn Hạnh, quận 10, HCM',
      favorite: 5,
      phone: '0966216565',
      email: 'tieuhoatrendsmile@gmail.com',
      location: '255 Bùi viện, Quận 1, TPHCM',
      nameH: 'Hệ thống bệnh viện thế giới',
      time: 'Th2 - CN từ 9h - 20h',
      totalRate: 4.5,
      rating: '45 đánh giá',
      education:
          'Từ năm 2006 – 2012: Tốt nghiệp Viện đào tạo răng hàm mặt Đại học Y Hà Nội Từ năm 2013 – nay: Tham gia khóa đào tạo thực hành “Thiết kế nụ cười trong Nha khoa” cùng Dr. David Montalvo Arias (hiện đang làm việc tại Apa Aesthetics UAE) bậc thầy trong Thiết kế nụ cười Tham gia khóa đào tạo chuyên sâu “ Thẩm mỹ nội khoa không dao kéo” cùng Dr. David Dana (Education Director tại Progressive Orthodontic Seminars) Tham gia khóa đào tạo Phục hình Inlay, Công nghệ sứ sinh học trong phục hồi răng thẩm mỹ do Mani Schutz Dental tổ chức.'),
  Doctor(
      image: 'assets/images/doctor.png',
      name: 'Bác sĩ: Ỷ Thiên Kiếm',
      title: 'Bác sĩ - Chuyên gia bộ đồ lòng',
      specialist: 'Chuyên khoa: Tiêu hóa - Gan mật',
      address: '527 Sư Vạn Hạnh, quận 10, HCM',
      favorite: 5,
      totalRate: 4.5,
      phone: '0966216565',
      email: 'tieuhoatrendsmile@gmail.com',
      location: '255 Bùi viện, Quận 1, TPHCM',
      nameH: 'Hệ thống bệnh viện thế giới',
      time: 'Th2 - CN từ 9h - 20h',
      rating: '45 đánh giá',
      education:
          'Từ năm 2006 – 2012: Tốt nghiệp Viện đào tạo răng hàm mặt Đại học Y Hà Nội Từ năm 2013 – nay: Tham gia khóa đào tạo thực hành “Thiết kế nụ cười trong Nha khoa” cùng Dr. David Montalvo Arias (hiện đang làm việc tại Apa Aesthetics UAE) bậc thầy trong Thiết kế nụ cười Tham gia khóa đào tạo chuyên sâu “ Thẩm mỹ nội khoa không dao kéo” cùng Dr. David Dana (Education Director tại Progressive Orthodontic Seminars) Tham gia khóa đào tạo Phục hình Inlay, Công nghệ sứ sinh học trong phục hồi răng thẩm mỹ do Mani Schutz Dental tổ chức.'),
  Doctor(
      image: 'assets/images/doctor3.png',
      name: 'Bác sĩ: Chu Chỉ Nhược',
      title: 'Bác sĩ - Chuyên gia bộ đồ lòng',
      specialist: 'Chuyên khoa: Tiêu hóa - Gan mật',
      address: '527 Sư Vạn Hạnh, quận 10, HCM',
      favorite: 5,
      totalRate: 4.5,
      phone: '0966216565',
      email: 'tieuhoatrendsmile@gmail.com',
      location: '255 Bùi viện, Quận 1, TPHCM',
      nameH: 'Hệ thống bệnh viện thế giới',
      time: 'Th2 - CN từ 9h - 20h',
      rating: '45 đánh giá',
      education:
          'Từ năm 2006 – 2012: Tốt nghiệp Viện đào tạo răng hàm mặt Đại học Y Hà Nội Từ năm 2013 – nay: Tham gia khóa đào tạo thực hành “Thiết kế nụ cười trong Nha khoa” cùng Dr. David Montalvo Arias (hiện đang làm việc tại Apa Aesthetics UAE) bậc thầy trong Thiết kế nụ cười Tham gia khóa đào tạo chuyên sâu “ Thẩm mỹ nội khoa không dao kéo” cùng Dr. David Dana (Education Director tại Progressive Orthodontic Seminars) Tham gia khóa đào tạo Phục hình Inlay, Công nghệ sứ sinh học trong phục hồi răng thẩm mỹ do Mani Schutz Dental tổ chức.'),
  Doctor(
      image: 'assets/images/doctor.png',
      name: 'Bác sĩ: Trương Vô Kỵ',
      title: 'Bác sĩ - Chuyên gia bộ đồ lòng',
      specialist: 'Chuyên khoa: Tiêu hóa - Gan mật',
      address: '527 Sư Vạn Hạnh, quận 10, HCM',
      favorite: 5,
      totalRate: 4.5,
      phone: '0966216565',
      email: 'tieuhoatrendsmile@gmail.com',
      location: '255 Bùi viện, Quận 1, TPHCM',
      nameH: 'Hệ thống bệnh viện thế giới',
      time: 'Th2 - CN từ 9h - 20h',
      rating: '45 đánh giá',
      education:
          'Từ năm 2006 – 2012: Tốt nghiệp Viện đào tạo răng hàm mặt Đại học Y Hà Nội Từ năm 2013 – nay: Tham gia khóa đào tạo thực hành “Thiết kế nụ cười trong Nha khoa” cùng Dr. David Montalvo Arias (hiện đang làm việc tại Apa Aesthetics UAE) bậc thầy trong Thiết kế nụ cười Tham gia khóa đào tạo chuyên sâu “ Thẩm mỹ nội khoa không dao kéo” cùng Dr. David Dana (Education Director tại Progressive Orthodontic Seminars) Tham gia khóa đào tạo Phục hình Inlay, Công nghệ sứ sinh học trong phục hồi răng thẩm mỹ do Mani Schutz Dental tổ chức.'),
  Doctor(
      image: 'assets/images/doctor2.png',
      name: 'Bác sĩ: Tạ Tốn',
      title: 'Bác sĩ - Chuyên gia bộ đồ lòng',
      specialist: 'Chuyên khoa: Tiêu hóa - Gan mật',
      address: '527 Sư Vạn Hạnh, quận 10, HCM',
      favorite: 5,
      totalRate: 4.5,
      phone: '0966216565',
      email: 'tieuhoatrendsmile@gmail.com',
      location: '255 Bùi viện, Quận 1, TPHCM',
      nameH: 'Hệ thống bệnh viện thế giới',
      time: 'Th2 - CN từ 9h - 20h',
      rating: '45 đánh giá',
      education:
          'Từ năm 2006 – 2012: Tốt nghiệp Viện đào tạo răng hàm mặt Đại học Y Hà Nội Từ năm 2013 – nay: Tham gia khóa đào tạo thực hành “Thiết kế nụ cười trong Nha khoa” cùng Dr. David Montalvo Arias (hiện đang làm việc tại Apa Aesthetics UAE) bậc thầy trong Thiết kế nụ cười Tham gia khóa đào tạo chuyên sâu “ Thẩm mỹ nội khoa không dao kéo” cùng Dr. David Dana (Education Director tại Progressive Orthodontic Seminars) Tham gia khóa đào tạo Phục hình Inlay, Công nghệ sứ sinh học trong phục hồi răng thẩm mỹ do Mani Schutz Dental tổ chức.'),
  Doctor(
      image: 'assets/images/doctor2.png',
      name: 'Bác sĩ: Đồ Thiên Long',
      title: 'Bác sĩ - Chuyên gia bộ đồ lòng',
      specialist: 'Chuyên khoa: Tiêu hóa - Gan mật',
      address: '527 Sư Vạn Hạnh, quận 10, HCM',
      favorite: 5,
      totalRate: 4.5,
      phone: '0966216565',
      email: 'tieuhoatrendsmile@gmail.com',
      location: '255 Bùi viện, Quận 1, TPHCM',
      nameH: 'Hệ thống bệnh viện thế giới',
      time: 'Th2 - CN từ 9h - 20h',
      rating: '45 đánh giá',
      education:
          'Từ năm 2006 – 2012: Tốt nghiệp Viện đào tạo răng hàm mặt Đại học Y Hà Nội Từ năm 2013 – nay: Tham gia khóa đào tạo thực hành “Thiết kế nụ cười trong Nha khoa” cùng Dr. David Montalvo Arias (hiện đang làm việc tại Apa Aesthetics UAE) bậc thầy trong Thiết kế nụ cười Tham gia khóa đào tạo chuyên sâu “ Thẩm mỹ nội khoa không dao kéo” cùng Dr. David Dana (Education Director tại Progressive Orthodontic Seminars) Tham gia khóa đào tạo Phục hình Inlay, Công nghệ sứ sinh học trong phục hồi răng thẩm mỹ do Mani Schutz Dental tổ chức.'),
];
